title: "Brasília BitDevs"
tagline: "Brasília BitDevs é uma comunidade para aqueles interessados em discutir e participar na pesquisa e desenvolvimento do Bitcoin e protocolos relacionados."

menu:
  - { name: "Eventos", url: "/events" }
  - {
      name: "Meetup",
      url: "https://www.meetup.com/pt-BR/brasilia-bitcoin/",
      external: true,
    }
  - { name: "Cidades", url: "/cities" }
