title: 'BitDevs'
tagline: 'BitDevs is a community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Blog', url: '/blog'}
  - {name: 'Cities', url: '/cities'}
  - name: 'New York City'
    submenu:
      - {name: 'Events', url: '/events'}
      - {name: 'Meetup', url: 'https://www.meetup.com/BitDevsNYC/', external: true}
      - {name: 'Luma', url: 'https://luma.com/calendar/cal-BocajELvgRuxaCx', external: true}
  
